from .simple_vertex_scene import *
from .index_vertex_scene import *
from .colour_vertex_scene import *
from .texture_scene import *
from .advanced_material_scene import *
from .light_scene import *
from .material_scene import *
from .cube_moving_scene import *
from .advanced_moving_scene import *
from .dodecahedron_moving_scene import *
from .base import *